---

kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.16
    commands:
      - go test -v -race -parallel 4 ./...

  - name: golangci-lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run

  - name: build
    image: golang:1.16
    commands:
      - go build -v ./...
